<?php

namespace AppBundle\Repository;

/**
 * CameraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CameraRepository extends \Doctrine\ORM\EntityRepository
{
}
