<?php

namespace AppBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param string $order
   *
   * @return result
   */
    public function orderByVotes($order = 'DESC')
    {
      $qb = $this->_em->createQueryBuilder();
      $qb->select('u, COUNT(v.id) AS HIDDEN countVotes')
          ->from($this->_entityName, 'u')
          ->innerJoin('u.votes', 'v')
          ->groupBy('u.id')
          ->orderBy('countVotes', $order);
      return $qb->getQuery()->getResult();
    }
}
