<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param string $role
   *
   * @return array
   */
    public function findEmailsByRole($role)
    {
      $qb = $this->_em->createQueryBuilder();
      $qb->select('u')
          ->from($this->_entityName, 'u')
          ->where('u.roles LIKE :roles')
          ->setParameter('roles', '%'.$role.'%');
      $result = $qb->getQuery()->getResult();
      $mails = [];
      foreach ($result as $key => $utilisateur) {
        $mails[] = $utilisateur->getEmail();
      }
      return $mails;
    }
}
