# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]



    admin.camera:
        class: AppBundle\Admin\CameraAdmin
        arguments: [~, AppBundle\Entity\Camera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Caméra', label: Lister les caméras,  icon: '<i class="fa fa-video-camera"></i>', position:right }

    admin.media:
        class: AppBundle\Admin\MediaAdmin
        arguments: [~, AppBundle\Entity\Media, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Média', label: Lister les médias,  icon: '<i class="fa fa-picture-o"></i>', position:right }

    admin.utilisateur:
        class: AppBundle\Admin\UtilisateurAdmin
        arguments: [~, AppBundle\Entity\Utilisateur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Utilisateur', label: Lister les utilisateurs,  icon: '<i class="fa fa-user-o"></i>', position:right }

    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Contact',  label: Contact,  icon: '<i class="fa fa-envelope"></i>', position:right }

    app.media_service:
        arguments:  ['@session', '@doctrine', '@security.token_storage']
        class: AppBundle\Service\MediaService

    app.iframe_service:
        arguments:  ['@request_stack', '@router']
        class: AppBundle\Service\IframeService
